### ISSUE TITLE
Doesn't work with latest react/*

### ISSUE THREAD

**Issue by digitv** [beaucollins/phluid-php#11]
Your framework is incompatible with latest versions of react/* packages. Will you roll out new version or this repo is abandoned?

**Comment by beaucollins** [comment]
I updated the packagist file to relax the `react/react` constraint and published version `0.2.0`. I'm not seeing any issues with `react/react@0.4.0`

**Comment by digitv** [comment]
I mean reactphp/http, socket , server, response methods changed

**Comment by beaucollins** [comment]
You'll have to point to some more concrete examples. The unit tests pass with `react/react@0.4.4` which includes [`react/http@0.4.4`](https://github.com/beaucollins/phluid-php/blob/master/composer.lock#L340-L352) and `react/socket@0.4.4`.

There's no information about changes for `react/react@0.5.x` at this point.

**Comment by beaucollins** [comment]
Looks like `react@0.5.x` makes bigger changes. There's no plans at this point to update this library.
