### ISSUE TITLE
Tag a release for packagist

### ISSUE THREAD

**Issue by afk11** [beaucollins/phluid-php#4]
Hi, I found your repository and wanted to try it out, but you haven't tagged a stable release for packagist. Any chance you could `git tag 0.0.1 && git push --tags` on master? 

Thanks!

**Comment by beaucollins** [comment]
@afk11 [Done](https://github.com/beaucollins/phluid-php/tree/0.0.1)!

This project is not maintained nor used anywhere as far as I know.

Happy hacking.
