### ISSUE TITLE
put and delete requests?

### ISSUE THREAD

**Issue by masiarb** [beaucollins/phluid-php#6]
Is there a way to listen for such HTTP methods? I checked in the source and apparently you totally ignored them. Let alone HEAD and OPTIONS...

**Comment by beaucollins** [comment]
There are no convenience methods [like `get` and `post`](https://github.com/beaucollins/phluid-php/blob/master/src/Phluid/App.php#L146-L148) but you can do this:

```php
$this->handle( 'HEAD', function($req, $res) {
   // handle the HTTP VERB
});
```
