### ISSUE TITLE
Non handled query stucks

### ISSUE THREAD

**Issue by pinkvoid** [beaucollins/phluid-php#8]
Hi
when a non handled query like /test is provided, the connection hangs.

What would be a better response is a 404.

**Comment by beaucollins** [comment]
This framework makes no assumptions about how the application should work. You can add a fallback route that would respond with a 404:

```php
// matches any route
$any = function() {
  return true;
};

// last route/endpoint configured for the app will respond to all requests not
// handled by the app.
$app->route( $any, function( $request, $response ) {
  $response->renderText( 'not found', 'text/plain', 404 );
} );
