### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by bawasaab** [beaucollins/phluid-php#9]
when i run composer install

Problem 1
    - Installation request for phluid/phluid master-dev -> satisfiable by phluid/phluid[dev-master].
    - phluid/phluid dev-master requires react/react dev-master -> satisfiable by react/react[dev-master] but these conflict with your requ
irements or minimum-stability.

**Comment by beaucollins** [comment]
Looks like iv you use `master-dev` instead of `dev-master` it works. Not sure what the underlying issue is at this point.
